services:
  ldap:
    hostname: ${LDAP_HOST}
    build:
      context: ../..
      dockerfile: docker/docker-files/ldap/Dockerfile.ldap.one_app
    environment:
      TZ: ${TIME_ZONE}
      LDAP_LOG_LEVEL: ${LDAP_LOG_LEVEL}
    volumes:
      - ldap_db:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - peresvet

volumes:
  ldap_db: {}
  ldap_config: {}

networks:
  peresvet:
    driver: bridge
    ipam:
      config:
          - subnet: 10.66.0.0/16
            gateway: 10.66.0.1