services:
  
  certbot:
    container_name: certbot
    hostname: certbot
    image: certbot/certbot
    volumes:
      - ../../certificates/certbot/www/:/var/www/certbot/:rw
      - ../../certificates/certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - peresvet

networks:
  peresvet:
    driver: bridge
    ipam:
      config:
          - subnet: 10.66.0.0/16
            gateway: 10.66.0.1