services:
  redis:
    image: redis/redis-stack:7.2.0-v6
    hostname: ${HOST_REDIS}
    networks:
      - peresvet
    environment:
      TZ: ${TIME_ZONE}
    restart: "no"

networks:
  peresvet:
    driver: bridge
    ipam:
      config:
          - subnet: 10.66.0.0/16
            gateway: 10.66.0.1